# Generated by Django 3.1.1 on 2020-09-22 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('L', 'Lançamento de Dardo'), ('C', '100m rasos')], max_length=1)),
                ('competicao_ativa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('unidade', models.CharField(max_length=1)),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='modalidades.competicao')),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
    ]
